# File cấu hình ứng dụng Spring Boot (Cấu hình Database SQL Server, Server port, JavaMailSender).
# Ngày thực hiện: 04/06/2026
# Tạo bởi: DuongND_HE186619
spring.application.name=cinema

# C\u1EA5u h\u00ECnh SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sample;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.servlet.context-path=/cinema
server.port=8081

# Cấu hình gửi Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# ĐIỀN EMAIL CỦA BẠN VÀO ĐÂY (VD: nguyenvanA@gmail.com)
spring.mail.username=duongndhe186619@fpt.edu.vn
# ĐIỀN MẬT KHẨU ỨNG DỤNG (APP PASSWORD) CỦA GMAIL VÀO ĐÂY (16 ký tự, không có dấu cách)
spring.mail.password=xrsj exzj jmqf tjwh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true